jmxUrl: http://localhost:10002/jmx
lowercaseOutputName: true
lowercaseOutputLabelNames: true
blacklistObjectNames: ["org.apache.derby:*", "org.apache.logging.log4j2:*", "com.jolbox.bonecp:*"]

rules:
- pattern: 'metrics<name=(.+)><>(Count|Value)'
  name: hive_metrics_$1_$2

- pattern: "java.lang.*"
